name: Build and deploy ASP.Net Core app to Azure Web App - pds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # ou a versão que está no seu api.csproj

      - name: Build with dotnet
        run: dotnet build ./api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./api.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6951BFFA3DB143579BE61DE68F6991D4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E4A1F5DA0F94B98BDB65254E4B35B49 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0A641CC307148CC8871BA57876A5872 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pds'
          slot-name: 'Production'
          package: ./
