name: Build and deploy ASP.Net Core app to Azure Web App - pds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build ./api/api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./api/api.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: List files in dotnet-app folder
        run: ls -la ./dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_383F6861026D4C8CBBFBFBD10A19DD94 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A846F26BFEA4808A1BCD28EB79482A8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DF8DF132E94D4F90A9AFDFE72ABF6543 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pds'
          slot-name: 'Production'
          package: ./dotnet-app
